email.username=dimaskywalker2002@mail.ru
email.password=WapQsRXbMExHJGpTmNww
email.from=dimaskywalker2002@mail.ru
mail.smtp.host=smtp.mail.ru
mail.smtp.port=465
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.ssl.enable=true